Merged in my changes to get things working on copson by submitting run.csh directly to the queue.
Also swapped the nodelist and 'create directory_snap file' code since
if a nodelist isn't found local_disc can be disabled.

Wolf: The way the nodelist was found differed dramatically after your partial rewrite and I don't quite see why/how etc. Would you check that bit over in
getconf.csh and copy-snapshots please.

diff --git a/bin/copy-snapshots b/bin/copy-snapshots
--- a/bin/copy-snapshots
+++ b/bin/copy-snapshots
@@ -24,7 +24,16 @@ if ($#argv > 0) then
 endif
 
 set targetdir = $PWD/data
-set nodelist = (`echo $NODELIST | sed 's/:/ /'`) # unpack NODELIST
+
+if ($?PBS_NODEFILE) then
+  set nodelist = `cat $PBS_NODEFILE`
+  set nodelist = (`echo $NODELIST | sed 's/:/ /'`) # unpack NODELIST
+else if (-e $HOME/.score/ndfile.$JOB_ID) then
+  set nodelist = `cat $HOME/.score/ndfile.$JOB_ID`
+else
+  echo "WARNING: Cannot find node list, continuing without local disk access"
+  set local_disc=0
+endif
 
 if ($debug) then
   echo "SCRATCH_DIR = $SCRATCH_DIR"
