Added the option to have *local files in run dir or src but not both

diff --git a/bin/pc_newrun b/bin/pc_newrun
--- a/bin/pc_newrun
+++ b/bin/pc_newrun
@@ -81,18 +81,33 @@ $PENCIL_HOME/bin/pc_mkdatadir
 [ -e data/new_from.dir ] || touch data/new_from.dir
 (echo $olddir; /bin/date) >> data/new_from.dir
 #
-#  make src dir and go there
-#
+#  make src dir and copy .local files to the same dir as original
+# 
   mkdir src
-  cd src
 #
-#  use *.local files from previous src directory
-#  and run pc_setupsrc
-#
-  echo "old source directory: " $olddir/src
-  cp $olddir/src/*.local .
-  echo "Use *.local files from:" `pwd`; ls -l *.local
-  cd ..
+  for f in Makefile.local cparam.local; do
+      in_run=0
+      in_src=0
+
+      if [ -f "$olddir/$f" ] && [ ! -h "$olddir/$f" ]; then in_run=1; fi
+      if [ -f "$olddir/src/$f" ] && [ ! -h "$olddir/src/$f" ]; then in_src=1; fi
+
+      if [ $in_run -eq 1 ] && [ $in_src -eq 1 ]; then
+          echo "Error: $f exists in both run directory and src as regular files! Please remove one." >&2; exit 1
+      elif [ $in_run -eq 0 ] && [ $in_src -eq 0 ]; then
+          echo "Error: $f does not exist in either run directory or src. Please add those files." >&2; exit 1
+      elif [ $in_run -eq 1 ] && [ $in_src -eq 0 ]; then
+          echo "old run directory: " $olddir
+          cp $olddir/*.local .
+          echo "Use *.local files from:" `pwd`; ls -l $f
+      elif [ $in_run -eq 0 ] && [ $in_src -eq 1 ]; then
+          echo "old source directory: " $olddir/src
+          cd src
+          cp $olddir/src/*.local .
+          echo "Use *.local files from:" `pwd`; ls -l $f
+          cd ..
+      fi
+  done
 #
   if [ -d $olddir/initial_condition ]; then
      echo "copying existing initial condition directory"
@@ -107,7 +122,7 @@ $PENCIL_HOME/bin/pc_mkdatadir
 #
   [ -f $parentdir/bin/pc_setupsrc.local ] && $parentdir/bin/pc_setupsrc.local
 #
-#  continue with the usual setup procedure
+#  continue with the usual setup procedure: run pc_setupsrc
 #
   if [ $same_source ]; then
     $PENCIL_HOME/bin/pc_setupsrc --min
diff --git a/bin/pc_setupsrc b/bin/pc_setupsrc
--- a/bin/pc_setupsrc
+++ b/bin/pc_setupsrc
@@ -621,6 +621,23 @@ link_root_makefile
 make_src_dir
 if [ "$link_all" -eq 1 ]; then link_src_files; fi
 #
+# Adapting to new structure with cparam.local and Makefile.local in run dir OR src 
+for f in Makefile.local cparam.local; do
+    in_run=0
+    in_src=0
+    if [ -f "$f" ] && [ ! -h "$f" ]; then in_run=1; fi
+    if [ -f "src/$f" ] && [ ! -h "src/$f" ]; then in_src=1; fi
+    if [ $in_run -eq 1 ] && [ $in_src -eq 1 ]; then
+        echo "Error: $f exists in both run directory and src as regular files" >&2; exit 1
+    elif [ $in_run -eq 0 ] && [ $in_src -eq 0 ]; then
+        echo "Error: $f does not exist in either run directory or src/" >&2; exit 1
+    elif [ $in_run -eq 1 ] && [ $in_src -eq 0 ]; then
+        if [ -h "src/$f" ]; then rm -f "src/$f"; fi
+        ln -s "../$f" "src/$f"
+        # echo "Linked local file: $f"
+    fi
+done
+#
 make_pre_and_post_processing_dir
 if [ "$link_all" -eq 1 ]; then link_pre_and_post_processing_files; fi
 #
