Check whether top is available at all

diff --git a/bin/remote-top b/bin/remote-top
--- a/bin/remote-top
+++ b/bin/remote-top
@@ -3,11 +3,23 @@
 # Name:   remote-top
 # Author: wd+ab
 # Date:    7-Oct-2002
-# $Id: remote-top,v 1.3 2003-08-28 15:51:24 dobler Exp $
+# $Id: remote-top,v 1.4 2003-08-30 16:59:15 dobler Exp $
 # Description:
 #     does top -bn1 on all procs of nodelist, write to datadir
 
 set debug = 0
+
+# Unpack NODELIST to csh array
+set nodelist = `echo "$NODELIST" | sed 's/:/ /g'`
+
+# Check for existence of `top' command:
+set node = $nodelist[1]
+set top_cmd = 'top -bn1 2>&1 > /dev/null; echo $?'
+set top_stat = `$SSH $node "sh -c '$top_cmd'"`
+if ("$top_stat" != "0") then         # return status should be 0
+  echo "remote-top: Can't find top command on $node"
+  exit 1
+endif
 
 if ($#argv > 0) then
   if (($1 == "-v") || ($1 == "--verbose")) then
@@ -17,9 +29,6 @@ if ($#argv > 0) then
 endif
 
 set targetdir = $PENCIL_WORKDIR/data
-
-# Unpack NODELIST to csh array
-set nodelist = `echo "$NODELIST" | sed 's/:/ /g'`
 
 if ($debug) then
   echo "targetdir = $targetdir"
